baseURL = "https://not-thien.github.io"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    name = "Information for the Concerned"
    title = "Thien's Portfolio"
    author = "Thien Nguyen"
    description = "Unit Testing since 2001"
    copyright = "© 2021 Thienager LLC"
    theme = "dark" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Thien Nguyen"
        photo = "images/creepy.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/not-thien/"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/not-thien"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "fab fa-instagram"
        url = "https://www.instagram.com/theadventuresofthienthien/"
        title = "Instagram"

        [[params.social.list]]
        icon = "fab fa-facebook"
        url = "https://www.facebook.com/theadventuresofthienthien/"
        title = "Facebook"
			

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Bachelor of Computer Science"
        college = "University of Minnesota - Twin Cties"
        dates = "2020 - 2023"
        thesis_title = "Historical Propensities of Human-Computer Interaction and Youth Culture"
        thesis_link = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"
				
        [[params.language.list]]
        language = "Vietnamese"
        level = "Native"

        [[params.language.list]]
        language = "Chinese"
        level = "Novice"

        [[params.language.list]]
        language = "Spanish"
        level = "Novice"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Volleyball"
		
		[[params.hobbies.list]]
        interest = "Cooking"

        [[params.hobbies.list]]
        interest = "Language Study"

        [[params.hobbies.list]]
        interest = "Gamer Girls"

    [params.aboutme]
        description = "Born and raised in Minnesota, USA but 100% Vietnamese American. I like the power of code and the planet I live on. So, I plan on developing climate solution applications and sustainability-focused products. I'm just tryna give my grandkids a better world than the one I inherited. Also, pineapples belong on pizza."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Undergraduate Researcher"
        dates = "May 2021 - *Present*"
        company = "Institute of the Environment - UMN"
		link = "http://environment.umn.edu/discovery/gli/"
        details = "Cooperate with [Dr. James Gerber](http://environment.umn.edu/staff/james-gerber/) and [Dr. Paul West](http://environment.umn.edu/staff/paul-west/) in an [USAID project](https://www.arcgis.com/apps/Cascade/index.html?appid=dd7bd5aeb9344725a4f9d852e4056d9e) to analyze soil degradation in Senegal. Write scripts and algorithms with **Javascript and Python API in Google Earth Engine** for satellite map compsition and data analysis."

        [[params.jobs.list]]
        position = "Lab Member"
        dates = "Sept 2020 - May 2021"
		link = "https://sase-labs-2021.github.io/"
        company = "Society of Scientists & Engineers - Labs"
        details = "**Lead an interdisciplinary** subteam of five students in the [SASE Labs 2021 project](https://github.com/SASE-Labs-2021/gopher-a-bite/tree/master/src), honing leadership skills and learning the necessary tools as we went. Developed a web app using **ReactJS** frontend with **Flash** backend, with integrated map navigation, user and restaurant **database,** and **machine learning recommendation** system"

